/**
 * Writes packages/shared/src/registry-abi.ts from the Foundry artifact so the app and CLI share a typed ABI.
 *   forge build && pnpm --filter @proofshot/contracts abi
 */
import { readFileSync, writeFileSync } from "node:fs";

const artifact = JSON.parse(readFileSync(new URL("../out/Registry.sol/Registry.json", import.meta.url), "utf8"));
const out = new URL("../../packages/shared/src/registry-abi.ts", import.meta.url);
writeFileSync(
  out,
  `// Generated by contracts/tools/export-abi.ts — do not edit.\nexport const registryAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
);
console.log(`wrote ${out.pathname}`);
